"""
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
s = "a"
t = "aa"
sums = 0
for j in s:
    sums+=ord(j)
sumt = 0
for i in t: 
    sumt+=ord(i)
print (chr(sumt-sums))

#one liner from dis
print (list(map(ord, t)),list(map(ord, s)))
chr(sum(map(ord, t)) - sum(map(ord, s)))
